<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ТСН строй</title>
    <link href="../../../../resourses/css/bootstrap.css" rel="stylesheet">
    <link href="../../../../resourses/css/style.css" rel="stylesheet">
</head>
<body>
<div class="shadow-cont container" style="max-width:970px;">
    <div class="row" style="margin: 0px 60px;padding: 10px 0px;">
            <div class="col-md-4" style="padding-top:8px;">
                ЛОГОТИП
                <img style="display:none;" src="../../../../resourses/images/logo.png" height="45" alt="современные технологии строительства">
            </div>
            <div class="col-md-3 col-md-offset-2" style="color:#00458e">
                <span class="medium">Казань,</span><br>
                <span style="font-family:'GothamProLight';font-size:13px;">ул.Кремлевкая, 1</span><br>
                <span style="border-bottom: 1px dotted #00458e;"></span>
            </div>
            <div class="col-md-3" style="color:#00458e;">
                <span class="light">+7 800 800 80 80</span><br>
                <span class="light">+7 800 800 80 80</span><br>
                <span class="regular" style="border-bottom: 1px dotted #00458e;cursor:poiter;">Оставить заявку</span>
            </div>
    </div>
    <div class="row menu">
        <div style="margin: 0 60px;">
            <ul class="light">
                <li><a>О компании</a></li>
                <li><a>Услуги</a></li>
                <li><a>Наши работы</a></li>
                <li><a>Вопрос ответ</a></li>
                <li><a>Контакты</a></li>
            </ul>
        </div>
    </div>
    <div class="row" style="margin: 5px 76px;">
        <h1 style="font-size:14px;">
            <span class="medium">&emsp;О компании &mdash; </span> 
            <span class="light" style="font-size:13px;display:none;">
                предлагает весь комплекс строительных услуг, применяя новые технологии и современнные материалы. Мы готовы принять участие во всех циклах строительства: от разработки идеи и бюджет, до сдачи объекта под ключ.
            </span>
        </h1>
    </div>
    <div class="row">
        <div class="medium" style="margin: 5px 90px;font-size:22px;">
            Наши услуги:
        </div>
    </div>
    
    <div class="row" style='margin:0px 60px 10px;'>
        <div class="col-md-6">
            <div class='service-title'>
                Строительство Фундаментов
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/1.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Фундамент с подвалом</a></li>
                <li><a href="#">Плитный фундамент</a></li>
                <li><a href="#">Свайный фундамент</a></li>
                <li><a href="#">Ленточный фундамент</a></li>
                <li><a href="#">Фундамент на финтовых сваях</a></li>
                <li><a href="#">Утепленная шведская плита</a></li>
                <li><a href="#">Фундамент под забор</a></li>
            </ul>
            
        </div>
        <div class="col-md-6">
            <div class='service-title'>
                Строительство Коттеджей
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/2.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Проектирование коттеджей</a></li>
                <li><a href="#">Кирпичные коттеджи</a></li>
                <li><a href="#">Монолитные коттеджи</a></li>
            </ul>
        </div>
    </div>
    
    <div class="row" style='margin:10px 60px;'>
        <div class="col-md-6">
            <div class='service-title'>
                Укрепление Фундаментов
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/3.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Монолитное укрепление</a></li>
                <li><a href="#">Укрепление габионами</a></li>
                <li><a href="#">Укрепление матрацами Рено</a></li>
                <li><a href="#">Укрепление шпунтами ПВХ</a></li>
                <li><a href="#">Укрепление шпунтами Ларсена</a></li>
                <li><a href="#">Укрепление лиственницой</a></li>
                <li><a href="#">Укрепление георешеткой</a></li>
                <li><a href="#">Строительство пирсов и причалов</a></li>
            </ul>
            
        </div>
        <div class="col-md-6">
            <div class='service-title'>
                Укрепление Откосов
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/4.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Укрепление георешеткой</a></li>
                <li><a href="#">Укрепление матрацами Рено</a></li>
                <li><a href="#">Укрепление геоматоми</a></li>
                <li><a href="#">Укрепление биоматоми</a></li>
            </ul>
        </div>
    </div>
    
    <div class="row" style='margin:10px 60px;'>
        <div class="col-md-6">
            <div class='service-title'>
                Строительство Подпорных Стен
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/5.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Подпорные стены из монолита</a></li>
                <li><a href="#">Подпорные стены из габионов</a></li>
                <li><a href="#">Подпорные стены из ФБС</a></li>
                <li><a href="#">Подпорные стены из шпутов ПВХ</a></li>
                <li><a href="#">Подпорные стены из шпунтов ларсена</a></li>
                <li><a href="#">Подпорные стены из армированного грунта</a></li>
            </ul>
            
        </div>
        <div class="col-md-6">
            <div class='service-title'>
                Устройство Дренажей
            </div>
            <img class="img-thumbnail service-img" src="../../../../resourses/images/6.jpg" alt="Строительство Фундаментов">
            <ul class="service-list">
                <li><a href="#">Дренаж фундамента</a></li>
                <li><a href="#">Дренаж участка</a></li>
                <li><a href="#">Пристенный дренаж</a></li>
                <li><a href="#">Кольцевой дренаж</a></li>
                <li><a href="#">Пластовый дренаж</a></li>
            </ul>
        </div>
    </div>
    <div class="row footer">
        <div class="row" style="margin:45px 30px; color:#4a7099;">
            <div class="col-md-3" style="text-align:center;">
                <a href="http://insitespace.ru/">
                    <span class="regular" style="font-size:14px;">insite.space</span><br>
                    <span class="light" style="font-size:14px;">прокачай свой сайт</span>
                </a>
            </div>
            <div class="col-md-6" style="text-align:center;padding-top:4px;">
                <button id="btnSearch">
                    <img src="../../../../resourses/images/search.jpg">
                </button>
                <input  id="txtSearch" type="text">
            </div>
            <div  class="col-md-3 light" style="text-align:center;padding-top:12px; font-size:14px;">
                <a href="http://insitespace.ru/" style="border-bottom: 1px dotted #5D87B4;">
                    Карта сайта  
                </a>
            </div>
            <div class="col-md-12 light" style="text-align:center;color:#9cafc4;padding-top:20px;">
                &#169 2015 Компания
            </div>
        </div>
    </div>
</div>    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
</body>
</html>