<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Добавить изображение</h4>
            </div>
            <form id="formAddAlbum" method="post" action="javascript:void(null);" onsubmit="admin.showAddModalImage.addImage(this)">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Title
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="text" class="form-control" class='add_image' name="title_image" id="title_image" placeholder="Введите title изображения" required>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Alt
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="text" class="form-control" class='add_image' name="alt_image" id="alt_image" placeholder="Введите alt изображения" required>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Изображение
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="file"  onchange="admin.checkFile(this)" class='add_image' name="addFile"  id="addFile"  required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button id="submitAlbumModal" type="submit" class="btn btn-primary">Добавить</button>
                    <div class="alert alert-success successAlert"   role="alert" style="display: none;margin-top: 10px;"></div>
                    <div class="alert alert-danger dangerAlert"  role="alert" style="display: none;margin-top: 10px;"></div>
                </div>
            </form>
        </div>
    </div>
</div>



