<div class="modal fade" id="editImageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Редактировать изображение</h4>
            </div>
            <form id="formAddAlbum" method="post" action="javascript:void(null);" onsubmit="admin.showEditModalImage.clickBtn()">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Title
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="hidden" name="image_id" id="image_id">
                            <input type="text" class="form-control" name="edit_title_image" id="edit_title_image" placeholder="Введите title изображения" required>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Alt
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="text" class="form-control" name="edit_alt_image" id="edit_alt_image" placeholder="Введите alt изображения" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button id="submitEditImageModal" type="submit" class="btn btn-primary">Редактировать</button>
                </div>
            </form>
        </div>
    </div>
</div>



