<?php
$this->viewLayout('head');
?>
<meta name="description" content=""/>
<meta name="Keywords" content=""/>
<title>Каталог кальянных</title>
<link rel="stylesheet" type="text/css" href="../../../../resourses/hookah/css/cataloghookah.css">
</head>
<body>
    
    <div id="menu">
      <ul>
        <li><a href="">Карта</a></li>
        <li><a href="">Кальянные</a></li>
        <li><a href="">Магазины</a></li>
        <li><a href="">О сервисе</a></li>
      </ul>
    </div>
    
    <div class="wrap">
      
      <div id="params">
        
        <input type="text" class="form-control control-hmap" placeholder="Поиск по названию" />
        <button class="btn btn-red">Параметры <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></button>
          
        <div class="well">Список параметров для фильтрации...</div>
        
      </div>
      
      <div id="band-inform">
        <div class="band-inform-found">Найдено заведений: 3</div>
        <div class="band-inform-display">
          <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
          <span class="glyphicon glyphicon-th-list band-inform-active" aria-hidden="true"></span>
          <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="band"></div>
      
      <div class="post">
        <div class="post-img">
          <div class="post-rating">108</div>
          <div class="post-img-border">
	      <img src="../../../../resourses/hookah/images/catalog/1.jpg" alt="Hookah Place Mansion" />
          </div>
        </div>
        <div class="post-content">
          <h3 class="post-title"><a href="#">Hookah Place Mansion</a></h3>
          <p class="post-desc">HookahPlace Mansion - проект команды JohnCalliano, известного видеоблога о кальянах. Здесь вы найдете три этажа, выполненных в различных стилях, от темного до дачно-зеленого. Для любителей приставок есть еще один секретный этаж, где есть большой выбор приставок для больших и средних компаний.</p>
        </div>
        <div class="clearfix"></div>
        <div class="post-button">
          <a href="#">Посмотреть на карте</a>
          <a href="#">Подробнее</a>
        </div>
      </div>
      <div class="band"></div>
      
      <div class="post">
        <div class="post-img">
          <div class="post-rating">97</div>
          <div class="post-img-border">
            <img src="../../../../resourses/hookah/images/catalog/2.jpg" alt="Simon's" />
          </div>
        </div>
        <div class="post-content">
          <h3 class="post-title"><a href="#">Simon's</a></h3>
          <p class="post-desc">Интересное кальянное место с особой атмосферой внутри. Основной упор здесь делается на желании удивить и порадовать гостей лучшими кальянами, чтобы они высоко оценили качество дыма, табака и профессионализм кальянщиков Simon's.
            В стенах Simon's царит исключительная дружеская атмосфера, где людей объединяет не только любовь к кальяну и хорошим, редким сортам чая, но и игровые приставки, настольные игры, регулярные тематические кинопоказы, спортивные трансляции.</p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="band"></div>
      
      <div class="post">
        <div class="post-img">
          <div class="post-rating">64</div>
          <div class="post-img-border">
            <img src="../../../../resourses/hookah/images/catalog/3.jpg" alt="My Lounge Room" />
          </div>
        </div>
        <div class="post-content">
          <h3 class="post-title"><a href="#">My Lounge Room</a></h3>
          <p class="post-desc">Представляем Вашему вниманию кальянную My Lounge Room, открывшуюся в середине сентября 2014 года. Из особенностей заведения, которые сразу же бросаются в глаза стоит отметить стильный интерьер в приятных тонах, а так же круглосуточный график работы.
            Здесь регулярно проводят кинопоказы, а так же вечера живой музыки. Любителей кальяна ждут еженедельные дегустации и мастер-классы.</p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="band"></div>
      
    </div>
    
  </body>
</html>