<div class="modal fade" id="albumModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Создать Альбом</h4>
            </div>
            <form id="formAddAlbum" method="post" action="javascript:void(null);" onsubmit="admin.showAddModalAlbum.clickAddBtn()">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Название
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                            <input type="text" class="form-control" id="name_album" placeholder="Введите название" required>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            Главное Изображение
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <select id="selectMainAlbum" class="form-control">
                                
                            </select>
                        </div>
                        <div id="imageAlbum" class="col-md-3 col-sm-3 col-xs-3">
                            
                        </div>
                    </div>
                    <div class="row">
                        <div id="selectImageAlbum" class="btn btn-primary">
                            Изображения
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button id="submitAlbumModal" type="submit" class="btn btn-primary">Добавить</button>
                </div>
            </form>
        </div>
    </div>
</div>

