<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Земля</title>
	<link href="../../../../resourses/css/bootstrap.css" rel="stylesheet">
        <link href="../../../../resourses/css/land/admin_style.css" rel="stylesheet" />
        <link rel="stylesheet" href="../../../../resourses/js/land/leaflet.css" />
        <script src="../../../../resourses/js/land/land_admin.js"></script>
        <script src="../../../../resourses/js/land/leaflet.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>