<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Панель администратора</title>
        <!-- Bootstrap core CSS -->
        <link href="../../../../resourses/css/bootstrap.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="../../../../resourses/css/dashboard.css" rel="stylesheet">
        <link href="../../../../resourses/css/admin.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    </head>
    <body>