<div class="MapModule" id="editCottage">
    <div style="text-align: right;border-bottom: 1px solid grey;">
        <span onclick="land_admin.click_close(this);land_admin.clearMap();" style="padding: 10px; font-size: 20px;cursor: pointer;">&times;</span>
    </div>
    <form method="post" onsubmit="land_admin.edit_cottage(); return false;">
	<input id="id" class="input" type="hidden">
	<input id="index" class="input" type="hidden">
	<table>
	    <tbody>
		<tr>
		    <td>Название</td>
		    <td>
			<input id="edit_name_cottage" class="input" type="text" required="">
		    </td>
		</tr>
		<tr>
		    <td>Город</td>
		    <td>
			<select id="edit_city_cottage">
			</select>
		    </td>
		</tr>
		<tr>
		    <td>Водные объекты</td>
		    <td>
			<select id="edit_waterbody_cottage">
			    <option value="0">Нет</option>
			    <option value="1">Да</option>
			</select>
		    </td>
		</tr>
		<tr>
		    <td>Лес, парк</td>
		    <td >
			<select id="edit_forest_cottage">
			    <option value="0">Нет</option>
			    <option value="1">Да</option>
			</select>
		    </td>
		</tr>
		<tr>
		    <td>Цена за сотку</td>
		    <td><input id="edit_price_cottage" class="input" type="text" required=""></td>
		</tr>
		<tr>
		    <td>Email</td>
		    <td>
			<input id="edit_email_cottage" class="input"  required="">
		    </td>
		</tr>
		<tr>
		    <td>Сайт</td>
		    <td>
			<input id="edit_site_cottage" class="input" type="text" required="">
		    </td>
		</tr>
		<tr>
		    <td>Телефон</td>
		    <td>
			<input id="edit_phone_cottage" class="input" type="text" required="">
		    </td>
		</tr>
		<tr>
		    <td>О Коттедже</td>
		</tr>
		<tr>
		    <td colspan="2">
			<textarea style="width: 400px; height:200px;" id="edit_about_cottage"></textarea>
		    </td>
		</tr>
	    </tbody>
	</table>
	<div style="text-align: center;border-top: 1px solid grey;">
	    <input class="my_btn" type="submit"  style="cursor: pointer;width: 100%;border: none;font-size: 18px;padding: 10px;">
	</div>
    </form>
</div>

