<div class="modal fade bs-example-modal-sm" id="reestablish" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm">
	<div class="modal-content">
	    <form style="margin: 20px;" onsubmit="return h_auth.reestablish(this);" class="form-horizontal">
		<div class="form-group">
		    <label for="login" class="col-sm-2 control-label">Email</label>
		    <div class="col-sm-10">
			<input required type="email" name="email" class="form-control" placeholder="Введите email">
		    </div>
		</div>
		<div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
		      <button type="submit" class="btn btn-default">Восстановить</button>
		    </div>
		</div>
		<div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
			<div class="alert alert-info" id="alert-reestablish-info" role="alert">...</div>
		    </div>
		</div>
		</div>
	    </form>
	</div>
    </div>
</div>