<div class="container-fluid mn" style="background: #232A34;">
    <div class="container">
	<div class="navbar-header">
	    <button type="button" onclick="hookah.indent()" class="navbar-toggle collapsed btn" style="  background-color: #F25F5C;height:38px;width:38px;" data-toggle="collapse" data-target="#mn">

	    </button>
	    <div class="navbar-brand sh" style="color:#F25F5C;padding-left: 40px" href="#">Меню</div>
	</div>
	<div class="row">
	    <div class="col-offset-lg-1 col-md-offset-1 col-lg-11 col-md-11 col-sm-12">
		<div class="navbar-collapse collapse" id="mn" aria-expanded="false">
		    <ul  class="nav navbar-nav">
			<li>
			    <div id="find" style="display: none;">
				рядом со мной
			    </div>
			</li>
			<li><a href="/hookah/cataloghookah/index">Кальянные</a></li>
			<li><a href="#">Mагазины</a></li>
			<li><a href="#">Предложить новость</a></li>
			<li><a href="#">Статьи</a></li>
			<li><a href="#">Видео</a></li>
			<li><a href="#">О сервисе</a></li>
			<li>
			    <a href="/hookah/authorization/index">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
			    </a>
			</li>
		    </ul>
		</div>
	    </div>
	</div>
    </div>
</div>